//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TODOListInteligence.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TODOListInteligence.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tareas agregadas.
        /// </summary>
        internal static string AddedTasksLabel {
            get {
                return ResourceManager.GetString("AddedTasksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string AddTaskButton {
            get {
                return ResourceManager.GetString("AddTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar tarea.
        /// </summary>
        internal static string AddTaskTitle {
            get {
                return ResourceManager.GetString("AddTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empezar ahora.
        /// </summary>
        internal static string ButtonWelcomePage {
            get {
                return ResourceManager.GetString("ButtonWelcomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delegar.
        /// </summary>
        internal static string Delegate {
            get {
                return ResourceManager.GetString("Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desechar o archivar.
        /// </summary>
        internal static string DiscardOrArchive {
            get {
                return ResourceManager.GetString("DiscardOrArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribuir tareas.
        /// </summary>
        internal static string DistributeTasksButton {
            get {
                return ResourceManager.GetString("DistributeTasksButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar de inmediato.
        /// </summary>
        internal static string DoNow {
            get {
                return ResourceManager.GetString("DoNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron preguntas..
        /// </summary>
        internal static string ErrorNoQuestions {
            get {
                return ResourceManager.GetString("ErrorNoQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        internal static string FinishButtonText {
            get {
                return ResourceManager.GetString("FinishButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importante.
        /// </summary>
        internal static string ImportanceLabel {
            get {
                return ResourceManager.GetString("ImportanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Bienvenido!.
        /// </summary>
        internal static string LabelTextWelcome {
            get {
                return ResourceManager.GetString("LabelTextWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No importante.
        /// </summary>
        internal static string NotImportant {
            get {
                return ResourceManager.GetString("NotImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No urgente.
        /// </summary>
        internal static string NotUrgentText {
            get {
                return ResourceManager.GetString("NotUrgentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planificar con exactitud y resolver.
        /// </summary>
        internal static string PlanAndResolve {
            get {
                return ResourceManager.GetString("PlanAndResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string TaskDescriptionLabel {
            get {
                return ResourceManager.GetString("TaskDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Describe la tarea.
        /// </summary>
        internal static string TaskDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("TaskDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la tarea.
        /// </summary>
        internal static string TaskNameLabel {
            get {
                return ResourceManager.GetString("TaskNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el nombre de la tarea.
        /// </summary>
        internal static string TaskNamePlaceholder {
            get {
                return ResourceManager.GetString("TaskNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Urgencia.
        /// </summary>
        internal static string UrgencyLabel {
            get {
                return ResourceManager.GetString("UrgencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Urgente.
        /// </summary>
        internal static string UrgentText {
            get {
                return ResourceManager.GetString("UrgentText", resourceCulture);
            }
        }
    }
}
